include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    prefer_const_constructors: true
    prefer_single_quotes: true
    prefer_const_declarations: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/l10n/*.dart"
  errors:
    invalid_annotation_target: ignore
